### ISSUE TITLE
"pdf corpora" ...

### ISSUE THREAD

**Issue by Albretch** [pdf-association/pdf-corpora#3]
to my understanding, the idea of using pdf files as the resident format in a corpus is so out of it "crazy" and wastefully so, that I wonder what could that possibly mean. I tried to start a discussion on such matters at the corpora list days ago:

// __ towards a "pan document format" (pun intended) ... 

 https://list.elra.info/mailman3/hyperkitty/list/corpora@list.elra.info/thread/4AULI3UUQ7BQG5ANFYGEEL7FXQXIILYN/
~
 I also checked your:

 https://github.com/pdf-association/pdf-corpora

 and most (if not all) aren't really corpora, but -text banks- apparently being used for functional and compliance testing, forensic research and such matters.

 Could you actually show examples of corpora which resident format is PDF? Optimally, examples which claims could be tested by oneself?

 lbrtchx

**Comment by petervwyatt** [comment]
This corpora index is targeted to PDF technology developers, as the corpora listed represent many of the realities in supporting the _file format_.
